---
- hosts: web
  tasks:
  - name: Install Docker
    ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
    
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
      
  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true
      
  - name: “Start Docker Service”
    service:
      name: docker
      state: started
      enabled: yes
      
  - name: "check docker sdk installed or not" 
    command: "pip3 list | grep docker"
    register: docker_sdk
  
  - name: "installing Docker SDK"
    pip:
         name: docker-py
    when: "docker_sdk.rc != 0"
    
  - name: "send html file"
    copy:
          src: index.html
          dest: /var/www/html
         
  - name: "downloading httpd image from dockerhub"
    community.general.docker_image: 
            name: httpd
            source: pull
            
  - name: "setting up docker container"
    docker_container:
            name: mywebserver
            image: httpd:latest
            state: started
            detach: true
            interactive: true
            ports: "8080:80"
            volumes: "/var/ww/html:/usr/local/apache2/htdocs/"
 
          
         
      
      
